name: Pull action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/banda-blog/
            git pull
            npm install
            tsc
            pm2 restart build/index.js
