name: Deploy action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git clone https://github.com/skibochka/banda-blog.git
            cd ~/banda-blog/
            touch .env
            echo "${{ secrets.DOT_ENV }}" >> .env
            touch ormconfig.yaml
            echo "${{ secrets.ORM_CONFIG }}" >> ormconfig.json
            npm install
            tsc
            pm2 start build/index.js
