name: Pull action
on: [push]
jobs:
  test:
    needs: [container-job]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 6375
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: getong/redis-action@v1
        with:
          redis version: '5.0.7'
          host port: 6379
          container port: 6379
      - name: set envs
        uses: allenevans/set-env@v2.0.0
        with:
          CURRENT_CONNECTION_NAME: test
          TEST_ORM_CONNECTION_NAME: test
          TEST_ORM_TYPE: sqlite
          TEST_ORM_DATABASE: blog.db
          TEST_ORM_ENTITIES: src/models/**/*.ts
          TEST_ORM_MIGRATIONS: src/migrations/**/*.ts
          TEST_ORM_ENTITIES_DIR: src/models
          TEST_ORM_MIGRATIONS_DIR: src/migrations

      - name: npm install and test
        run: |
          npm install
          npm test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test NodeJs app
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Pull NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/banda-blog/
            git pull
            rm -rf ormconfig.ts
            npm install
            tsc
            pm2 restart build/index.js
